Algoritmo "Estrutura_de_Repeticao"

Var
   x,y: inteiro


Inicio
      escreval("Digite dois numeros")
      leia(x)
      leia(y)
      
      enquanto x <> y faca
      
      se x < y entao
         escreval("Crescente")
      senao
         escreval("Decrecente")
      fimse
           escreval("Digite outro dois numeros")
           leia(x)
           leia(y)
      fimenquanto

Fimalgoritmo