Algoritmo "ESTRUTURA SEQUCINCIAL - parte 1 = nona consumo"

Var
         pecorrida, gasto, medio : real


Inicio

        escreval("digite o valor da distancia pecorrida: ")
        leia(pecorrida)
        
        escreval("digite o valor do combustivél gasto: ")
        leia(gasto)
        
        medio<- (pecorrida / gasto)
        
        escreval("Consumo medio: ", medio:8:3)




Fimalgoritmo