Algoritmo "Estrutura Sequencia - parte 1 = oitava consumo"

Var
   distanciaPecorrida, combustivelGasto, media : real


Inicio


      escreval("Digite a distancia pecorrida: ")
      leia(distanciaPecorrida)
      
      escreval("Digite o valor do Combustivél Gasto: ")
      leia(combustivelGasto)
      
      media <- (distanciaPecorrida+combustivelGasto) / 2

      escreval("Consumo Médio foi: ", media)

Fimalgoritmo