Algoritmo "exercicio_1"

Var
   X, Y : inteiro


Inicio

      escreval("Digite dois números: ")
      leia(X)
      leia(Y)

      enquanto X <> Y faca
      
      se X > Y entao
          escreval("Crescente")
      senao
           escreval("Decrescente")
      fimse
      
      escreval("Digite outros dois números:")
      leia(X)
      leia(Y)
      fimenquanto

Fimalgoritmo